# SAM template for deploying Lambda function with API Gateway endpoint
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler  # adjust to match your file/function
      Runtime: nodejs22.x     # or python3.11, etc.
      CodeUri: ./
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          OPENAI_API_KEY: XXX
          REDLINE_CHANNEL_WEBHOOK: XXX
          LYMPHAPRESS_CHANNEL_WEBHOOK: XXX
          BOT_TEST_CHANNEL_WEBHOOK: XXX
          ENVIRONMENT: XX
          TRELLO_KEY: XXX
          TRELLO_TOKEN: XXX
          TRELLO_BOARD_ID: XXX
          TRELLO_CALLBACK_URL: XXX
          TESTING: XX
          EVENT_BATCH_TABLE: !Ref EventBatchTable
          MAX_BATCH_SIZE: 5
          IS_LOCAL: true
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventBatchTable
      Events:
        WebhookAPI:
          Type: Api
          Properties:
            Path: /webhook
            Method: post

  EventBatchTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: event-batch-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: channelId
          AttributeType: S
      KeySchema:
        - AttributeName: channelId
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
